name = "rag-briefing"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".svelte-kit/cloudflare"

[[kv_namespaces]]
binding = "URLS_KV"
id = "80f6152bee1147ff8e9517c2ffe031a4"
